name: run date
on: 
  push:
    branches: 
      - main
jobs:
  show-date:
    runs-on: ubuntu-latest
    steps:
      - name: print run date
        run: |
           echo "Run started at: $(date -u)"
           echco "Local time: $(date)"
        
