name: while loop example
on: 
  push:
    branches: 
      - main
jobs:
  while-job:
    runs-on: ubuntu-latest
    steps:
      - name: run while loop
        run: |
          count=1 while [ $count -le 5 ] do
          echo "Count is $count"
          sleep 1
          count=$((count + 1))
          done
        
